#!/usr/bin/env bash

# -- Enable Completions -------------------------------------------------------

# enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        source /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        source /etc/bash_completion
    fi
fi

# enable completions for alias g='git'
# https://stackoverflow.com/a/39507158
source /usr/share/bash-completion/completions/git
__git_complete g __git_main

# enable github cli completion
if [ -x "$(command -v 'gh')" ]; then
    eval "$(gh completion -s bash)"
fi

# # enable fzf keybinds and completions
if [ -f ~/.config/fzf/fzf.bash ]; then
    source "$HOME/.config/fzf/fzf.bash"
    export FZF_DEFAULT_COMMAND='fd --type f \
        --strip-cwd-prefix --hidden --follow \
        --exclude .git'
fi
#
# if exists just; then
#     eval "$(just --completions bash)"
#     complete -F _just j # also complete for alias 'j'
# fi
# # -- End ----------------------------------------------------------------------
