# Alacritty Config
# https://alacritty.org/config-alacritty.html

# import a color scheme:
# general.import = ["~/.config/alacritty/colors/tokyonight.toml"]

terminal.shell = "tmux"

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"

[cursor]
blink_timeout = 0

[window]
decorations = "none"
dynamic_padding = true
padding = { x = 20, y = 10 }
opacity = 0.85

[font]
size = 18

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
