# Alacritty Config
# https://alacritty.org/config-alacritty.html

# Optionally import additional configs:
#import = ["~/.config/alacritty/colors.toml"]

shell = "tmux"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
padding = { x = 15, y = 10 }

[font]
size = 18

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
