
shell = "tmux"

[window]
padding = { x = 10, y = 5 }
#dynamic_padding = true
#opacity = 0.89
#startup_mode = "Maximized"
decorations = "none"

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
size = 18

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
