[colors.primary]
background        = "#282726"
foreground        = "#FFFCF0"
# dim_foreground    = "#FFFCF0"
# bright_foreground = "#FFFCF0"

[colors.cursor]
text = "#FFFCF0"
cursor = "#FFFCF0"

[colors.vi_mode_cursor]
text = "#FFFCF0"
cursor = "#FFFCF0"

[colors.normal]
black = "#100F0F"
red = "#AF3029"
green = "#66800B"
yellow = "#AD8301"
blue = "#205EA6"
magenta = "#A02F6F"
cyan = "#24837B"
white = "#FFFCF0"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[colors.dim]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"
