[colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"

[colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"

[colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"

[colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"

[colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"

[colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"

[colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"

[colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"

[colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"

[colors.normal]
black   = "#0a0b10"
blue    = "#005078"
cyan    = "#007676"
green   = "#015825"
magenta = "#4c0049"
red     = "#5e0009"
yellow  = "#6e5600"
white   = "#4f5258"

# additional greys from neovim hex
# grey1   = "#0a0b10" # (black)
# grey2   = "#1c1d23"
# grey3   = "#2c2e33"
# grey4   = "#4f5258" # (white)

[colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"

[colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"

# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"

# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"
