#!/usr/bin/env bash

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi

# enable completions for alias g='git'
# https://stackoverflow.com/a/39507158
source /usr/share/bash-completion/completions/git
__git_complete g __git_main

# github cli completion if installed
if [ -x "$(command -v 'gh')" ]; then
  eval "$(gh completion -s bash)"
fi

# enable fzf keybinds and completions
if [ -f ~/.config/fzf/fzf.bash ]; then
    source "$HOME/.config/fzf/fzf.bash"
    export FZF_DEFAULT_COMMAND='fd --type f \
        --strip-cwd-prefix --hidden --follow \
        --exclude .git'
fi

# exa is unmaintained, use eza instead
# https://github.com/eza-community/eza
if command -v eza >/dev/null 2>&1; then
    alias ls='eza -h -F --group-directories-first'
    # alias ll='eza -lhg'
    # alias lla='eza -alhg'
    alias tree='eza --tree'
    alias t2='tree --level=2'
    alias t3='tree --level=3'
fi

# enable zoxide
if [ -x "$(command -v 'zoxide')" ]; then
    eval "$(zoxide init bash)" && \
    alias cd='z'
fi

# load starship
if command -v starship >/dev/null 2>&1; then
    eval "$(starship init bash)"
fi

# load linux brew
if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_NO_ENV_HINTS='true'
    export HOMEBREW_PREFIX="$(brew --prefix)"

    # enable brew completions
    # https://docs.brew.sh/Shell-Completion
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
        done
    fi
fi
