#!/usr/bin/env bash

# Note: Ubuntu distributes GNOME Software as a Snap in versions 20.04 to 23.04,
# and replaced it with App Center in 23.10 and newer—neither of which support
# installing Flatpak apps. Installing the Flatpak plugin will also install a
# deb version of GNOME Software, resulting in two "Software" apps being
# installed at the same time on Ubuntu 20.04 to 23.04, and a single new
# \"Software\" app on Ubuntu 23.10 and newer.

flathub="https://dl.flathub.org/repo/flathub.flatpakrepo"

flatpaks=(
    "be.alexandervanhee.gradia"
    "com.github.tchx84.Flatseal"
    "com.slack.Slack"
    "com.spotify.Client"
    "com.transmissionbt.Transmission"
    "io.github.dvlv.boxbuddyrs"
    "io.github.flattool.Warehouse"
    "io.github.josephmawa.Bella"
    "io.missioncenter.MissionCenter"
    "org.audacityteam.Audacity"
    "org.audacityteam.Audacity"
    "org.audacityteam.Audacity.Codecs"
    "org.chromium.Chromium.Codecs"
    "org.gimp.GIMP.HEIC"
    "org.gnome.Loupe.HEIC"
    "org.gnome.NautilusPreviewer"
    "org.gnome.Papers"
    "org.libreoffice.LibreOffice"
    "org.remmina.Remmina"
    "org.wezfurlong.wezterm"
)

echo "Installing Flatpak..."
sudo -v

# Detect distro
distro=$(awk -F= '/^ID=/{print $2}' /etc/os-release | tr -d '"')

case "$distro" in
    debian|ubuntu)
        sudo apt update
        sudo apt install -y flatpak gnome-software-plugin-flatpak
        ;;
    fedora)
        # Rocky / RHEL
        # Note: fedora, centos stream, and alma include flatpak by default
        sudo dnf install -y flatpak
        ;;
    *)
        echo "Unsupported distro: $distro"
        return 1
        ;;
esac

echo "Adding Flathub repo..."

flatpak remote-add --if-not-exists flathub "$flathub"

echo "Installing Flatpaks..."

for pkg in "${flatpaks[@]}"; do
    flatpak install -y "$pkg"
done
