#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$script_dir/../fonts"
DST="$HOME/.local/share/"

if [ -e /etc/os-release ]; then
    source /etc/os-release
fi

if [[ $PRETTY_NAME == Fedora* ]]; then
    echo "hello, $PRETTY_NAME"
fi

echo "Copying Fonts..."
cp -rv "$SRC" "$DST"
