#!/usr/bin/env bash

mod=Alt
workspaces=9
terminal="$(command -v ghostty)"

echo "Configuring GNOME Settings..."

# swap caps for esc
gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"

# disable touchpad natural scroll
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll false

# config workspaces
gsettings set "org.gnome.shell.app-switcher" "current-workspace-only" "true"
gsettings set "org.gnome.desktop.wm.preferences" "num-workspaces" "$workspaces"
gsettings set "org.gnome.mutter" "dynamic-workspaces" "false"
gsettings set "org.gnome.mutter" "edge-tiling" "false"
gsettings set "org.gnome.mutter" "workspaces-only-on-primary" "true"

# workspace keybinds
for i in $(seq 1 "$workspaces"); do
    gsettings set "org.gnome.desktop.wm.keybindings" "switch-to-workspace-$i" "['<$mod>$i']"
    gsettings set "org.gnome.desktop.wm.keybindings" "move-to-workspace-$i" "['<Shift><$mod>$i']"
done

# close windows with `mod+shift+c`
gsettings set "org.gnome.desktop.wm.keybindings" "close" "['<Shift><$mod>c']"

# show the overview with `mod+space`
gsettings set "org.gnome.shell.keybindings" "toggle-overview" "['<$mod>space']"

# disable the built-in background logo watermark on fedora
if grep -qi fedora /etc/os-release; then
    gnome-extensions disable background-logo@fedorahosted.org
fi

# configure custom launch shortcuts

# launch terminal with `mod+return`
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Terminal"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "$terminal"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<$mod>Return"

# launch mission-center with `ctrl+shift+esc`
gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name "Mission Center"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command "flatpak run io.missioncenter.MissionCenter"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding "<Shift><Control>Escape"
