#!/usr/bin/env bash

pkg_common=(
    "at"
    "curl"
    "fastfetch"
    "fzf"
    "git"
    "jq"
    "just"
    "ripgrep"
    "rsync"
    "stow"
    "tree"
    "unzip"
    "wget"
    "zoxide"
    )

pkg_debian=(
    "ldnsutils"
    )

pkg_fedora=(
    "ldns-utils"
    "vim-enhanced"
    )

sudo -v

echo "Installing Packages..."

distro=$(
  awk -F= '/^ID=/{print $2}' /etc/os-release | tr -d '"'
)

if [ -z "$distro" ]; then
  echo "Error: could not detect distro" >&2
  exit 1
fi

case "$distro" in
    debian|ubuntu)
        sudo apt update
        sudo apt install -y "${pkg_common[@]}"
        sudo apt install -y "${pkg_debian[@]}"
        ;;
    fedora)
        sudo dnf install -y "${pkg_common[@]}"
        sudo dnf install -y "${pkg_fedora[@]}"
        ;;
    *)
        echo "Error: detected distro \"$distro\" is unsupported"
        return 1
        ;;
esac
