# Alacritty Config
# https://alacritty.org/config-alacritty.html

# import a color scheme:
# themes: https://github.com/alacritty/alacritty-theme/tree/master/themes
# general.import = ["~/.config/alacritty/colors/catppuccin-mocha.toml"]

#terminal.shell = "tmux"

# [env]
# TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"

[cursor]
blink_timeout = 0

[window]
decorations = "none"
dynamic_padding = true
padding = { x = 20, y = 10 }
opacity = 0.95

[font]
size = 14

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
